### ISSUE TITLE
Saved coordinates are shifted to the "Save center"

### ISSUE THREAD

**Issue by ki-dragon** [meesoft/PhotoLocator#1]
Hello,
Windows 10 64 Bit. Net 6.0.11 64 Bit. Tool version 22.6.22.0.
Tried to tag pictures manually several times but the saved coordinates in the picture seem to be always shifted.
Procedure: "Save center", "Apply location", "Save changes", click on the changed picture and it is shown somewhere nearby to the saved location but not there where it supposed to be.
Maybe there is a kind of value rounding issue?
Regards

**Comment by meesoft** [comment]
Sorry for late reply, for some reason Github does not send me e-mail notifications on new issues.
Anyway, you are right, there was a rounding issue which I will fix.

**Comment by meesoft** [comment]
Fixed in version 23.4.16
