### ISSUE TITLE
GPS Tagging overwrites / deletes part of the existing EXIF

### ISSUE THREAD

**Issue by ki-dragon** [meesoft/PhotoLocator#2]
Hello,
Windows 10 64 Bit. Net 6.0.11 64 Bit. Tool version 22.6.22.0.
After the GPS tag writing checked the EXIF content with IrfanView and it seems like complete block called "Maker Notes (Vendor)" (Canon specific?) is not there anymore.
Compared to the pictures tagged by GeoSetter and this block is still be there.
Maybe an GPS format issue. It is GPSVersionID 2.3.0.0 but GeoSetter uses 2.2.0.0
Regards

**Comment by meesoft** [comment]
I use the System.Windows.Media.Imaging.BitmapMetadata class in net6 to handle EXIF so at this point I'm not sure if I can do anything about it.

**Comment by meesoft** [comment]
Version 23.4.16 can now use ExifTool to save tags which should fix the issue
