### ISSUE TITLE
How to auto tag images based on Google Timeline

### ISSUE THREAD

**Issue by andyzukunft** [meesoft/PhotoLocator#6]
Hey,

I want to automise image tagging for my Japan trip in April. The github description says it supports either GPX or KML files as location origin. There are quiet some raw images which I want to tag based on a Google Timeline export.

I am also a .NET developer and have experience with WPF. If you are up for it I can provide assistance with some parts of your app. The following questions are partially from a developers view.

My questions:
- Clicking "Auto Tag" with or without having selected any images fells like it kills the app (loading screen, does not seem to continue for two minutes). I also tried it with my "jpeg export" folder which only contains about 100 images. Works with far fewer images within the folder. What's the amount of images you usually use for personal conversion or testing of performance? It seems to work with a test folder having one image (didn't do more testing here).
- I used Google Takeout to export the Maps Timeline data. That's the correct export, right (contains among others: Records.json, semantic location history as json splitted by year-month)? Which of those file should I use?
- As "Auto Tag" asks for a timestamp offset so I am assuming the EXIF timestamp does not contain a timezone / offset value (i.e. only local datetime)?
- Is there a reason why .raw/.arw images are not pre-selected in the app settings?

**Comment by meesoft** [comment]
Hi

When you click _Auto tag_ it waits for the metadata/exif from all images in the folder to be loaded. I just tried and on my PC it takes around 25 seconds for a folder with 300 jpeg images. I guess the speed might vary with disk speed, image type etc. I don't know if it can be done faster, but basically the metadata need to be loaded before the files can be tagged. You are of course welcome to see if you can make it faster.

I haven't tried _Google Takeout_ so I don't know what it does. The only way I have found to export the timeline is to select a day and then click _Export this day to KML_ in the menu on the gear icon in the bottom of the screen. I don't know if there is a good way to export many days,

It should not be necessary to specify a timestamp offset if your camera's time and timezone was set correctly. The primary reason I made this feature is that I have many times started a trip somewhere and only after some time realized that I forgot to set the time zone in my camera, so when I got home the pictures from the first day had the wrong time on them. Same thing after changing daylight saving time, if you forget to adjust the camera's time this offset can be handy.

I don't have any camera that produces .raw or .arw files (I mostly use Canon in addition to phones and drones) so I have never tested with these. If it works the formats are easily added in settings.

**Comment by andyzukunft** [comment]
You helped me a lot already.

I found the kml export on *Google Maps Timeline*. Didn't see it beforehand. The export seems to be based on "Semenatic Location History" (as named in the *Google Takeout* file). For my first test I had about five entries for a whole day. Everything in-between was not "located". I mean this is better than nothing but it does suck.

I identified the possibility to export the *Google Takeout* files to .gpx/.kml using [gotoextr](https://github.com/kpym/gotoextr). Based on a simple statement the application generates a .gpx file for e.g. a range of two months or even two years. *Photo Locator* works really performant even with a gpx file the size of 30 MB. It is really handy and you can get done a lot of things really quickly.

Regarding the "Auto Tag" window performance itself I identified the behaviour to be seamingly constrained / bottlenecked by the file amount within the folder. Using several hundreds .jpegs or .arw takes about the same time - I estimate. However the read rate (as shown in Task Manager) is several times higher (roughly 10 MB/s vs. 50 MB/s). The SSD can take around 5000 MB/s with a lot of IOPS so the limiting issue seems to be *exiftool*.

I played with *PhotoLocator*. It is really good that you provided the time offset field as I needed it for basically everything I located today. My timestamps in Japan where initially 12h and later on 7h "off". I think I set the timestamp later on. Still doesn't explain the initial 12h time offset. I needed the offset for several other imports of pictures taken the last couple of years.

Regarding changes to *PhotoLocator*. I already changed two/three things in the source code. One of them to circument an error with the longitude for London as exported by *gotoextr*. Do you prefer to get one single PR (Pull Request) contain specific changes or would you prefer one PR with several changes combined?

**Comment by meesoft** [comment]
Hi. Good to hear that you made it work. I have just made a commit to Master so that it displays actual progress when loading a folder before opening the Auto tag window. At  least that should give an idea how long you have to wait.
No one has made PRs to PhotoLocator yet so I'm not really sure what will work the best, but I think that I prefer smaller PRs. I cannot promise that I will accept them but I will if I find that the changes are generally useful and they follow the existing coding style.

**Comment by andyzukunft** [comment]
Sounds good. It's clear that not all PRs are being merged. That's the perogative of the source owner. We can discuss further in the upcoming PRs.
